### ISSUE TITLE
Testimonial not loaded properly in the editor

### ISSUE THREAD

**Issue by kafleg** [jadrowp/jadro#64]
**Describe the bug**
The testimonial pattern is not loading properly in the editor and images(gravatar) are missing. See the screenshot of the editor.

**To Reproduce**
1. Go to pages and add new
2. Add a Testimonial pattern in the page

**Screenshots**
![image](https://user-images.githubusercontent.com/13062231/236503888-e5622b80-cd4e-4a38-a97c-ffca21c1e6f1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - WP Version - 6.2

**Comment by maneshtimilsina** [comment]
Fixed
