### ISSUE TITLE
Team member not loaded properly

### ISSUE THREAD

**Issue by kafleg** [jadrowp/jadro#65]
**Describe the bug**
Team member is not loaded properly in the editor. Check the attached screenshot. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13062231/236504737-4e011721-5534-406d-8629-378cf087d414.png)

**Comment by ernilambar** [comment]
Can you please recheck the theme? I am not being able to reproduce this issue? Theme had issue with `get_theme_file_uri()` and we fixed that in this PR https://github.com/jadrowp/jadro/pull/57/files

**Comment by maneshtimilsina** [comment]
Fixed.
